<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  spfun,
  min_width,
  max_width,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  hsfrac,
  maxwords,
  maxsize,
  csites,
  strands,
  priors_file,
  reason_for_stopping,
  back_order,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT maxwords (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT back_order (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                alt CDATA ""
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.11.3" release="Fri Feb 19 13:23:06 2016 -0800">
<training_set datafile="common/adh.s" length="33">
<alphabet name="Protein" like="protein">
<letter id="A" symbol="A" name="Alanine" colour="0000CC"/>
<letter id="C" symbol="C" name="Cysteine" colour="0000CC"/>
<letter id="D" symbol="D" name="Aspartic acid" colour="FF00FF"/>
<letter id="E" symbol="E" name="Glutamic acid" colour="FF00FF"/>
<letter id="F" symbol="F" name="Phenylalanine" colour="0000CC"/>
<letter id="G" symbol="G" name="Glycine" colour="FFB300"/>
<letter id="H" symbol="H" name="Histidine" colour="FFCCCC"/>
<letter id="I" symbol="I" name="Isoleucine" colour="0000CC"/>
<letter id="K" symbol="K" name="Lysine" colour="CC0000"/>
<letter id="L" symbol="L" name="Leucine" colour="0000CC"/>
<letter id="M" symbol="M" name="Methionine" colour="0000CC"/>
<letter id="N" symbol="N" name="Asparagine" colour="008000"/>
<letter id="P" symbol="P" name="Proline" colour="FFFF00"/>
<letter id="Q" symbol="Q" name="Glutamine" colour="008000"/>
<letter id="R" symbol="R" name="Arginine" colour="CC0000"/>
<letter id="S" symbol="S" name="Serine" colour="008000"/>
<letter id="T" symbol="T" name="Threonine" colour="008000"/>
<letter id="V" symbol="V" name="Valine" colour="0000CC"/>
<letter id="W" symbol="W" name="Tryptophan" colour="0000CC"/>
<letter id="Y" symbol="Y" name="Tyrosine" colour="33E6CC"/>
<letter id="X" symbol="X" aliases="*." equals="ACDEFGHIKLMNPQRSTVWY" name="Any amino acid"/>
<letter id="B" symbol="B" equals="DN" name="Asparagine or Aspartic acid"/>
<letter id="Z" symbol="Z" equals="EQ" name="Glutamine or Glutamic acid"/>
<letter id="J" symbol="J" equals="IL" name="Leucine or Isoleucine"/>
</alphabet>
<sequence id="sequence_0" name="2BHD_STREX" length="255" weight="1.000000" />
<sequence id="sequence_1" name="3BHD_COMTE" length="253" weight="1.000000" />
<sequence id="sequence_2" name="ADH_DROME" length="255" weight="1.000000" />
<sequence id="sequence_3" name="AP27_MOUSE" length="244" weight="1.000000" />
<sequence id="sequence_4" name="BA72_EUBSP" length="249" weight="1.000000" />
<sequence id="sequence_5" name="BDH_HUMAN" length="343" weight="1.000000" />
<sequence id="sequence_6" name="BPHB_PSEPS" length="275" weight="1.000000" />
<sequence id="sequence_7" name="BUDC_KLETE" length="241" weight="1.000000" />
<sequence id="sequence_8" name="DHES_HUMAN" length="327" weight="1.000000" />
<sequence id="sequence_9" name="DHGB_BACME" length="262" weight="1.000000" />
<sequence id="sequence_10" name="DHII_HUMAN" length="292" weight="1.000000" />
<sequence id="sequence_11" name="DHMA_FLAS1" length="270" weight="1.000000" />
<sequence id="sequence_12" name="ENTA_ECOLI" length="248" weight="1.000000" />
<sequence id="sequence_13" name="FIXR_BRAJA" length="278" weight="1.000000" />
<sequence id="sequence_14" name="GUTD_ECOLI" length="259" weight="1.000000" />
<sequence id="sequence_15" name="HDE_CANTR" length="906" weight="1.000000" />
<sequence id="sequence_16" name="HDHA_ECOLI" length="255" weight="1.000000" />
<sequence id="sequence_17" name="LIGD_PSEPA" length="305" weight="1.000000" />
<sequence id="sequence_18" name="NODG_RHIME" length="245" weight="1.000000" />
<sequence id="sequence_19" name="RIDH_KLEAE" length="249" weight="1.000000" />
<sequence id="sequence_20" name="YINL_LISMO" length="248" weight="1.000000" />
<sequence id="sequence_21" name="YRTP_BACSU" length="238" weight="1.000000" />
<sequence id="sequence_22" name="CSGA_MYXXA" length="166" weight="1.000000" />
<sequence id="sequence_23" name="DHB2_HUMAN" length="387" weight="1.000000" />
<sequence id="sequence_24" name="DHB3_HUMAN" length="310" weight="1.000000" />
<sequence id="sequence_25" name="DHCA_HUMAN" length="276" weight="1.000000" />
<sequence id="sequence_26" name="FABI_ECOLI" length="262" weight="1.000000" />
<sequence id="sequence_27" name="FVT1_HUMAN" length="332" weight="1.000000" />
<sequence id="sequence_28" name="HMTR_LEIMA" length="287" weight="1.000000" />
<sequence id="sequence_29" name="MAS1_AGRRA" length="476" weight="1.000000" />
<sequence id="sequence_30" name="PCR_PEA" length="399" weight="1.000000" />
<sequence id="sequence_31" name="RFBB_NEIGO" length="346" weight="1.000000" />
<sequence id="sequence_32" name="YURA_MYXXA" length="258" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.111</value>
<value letter_id="C">0.012</value>
<value letter_id="D">0.050</value>
<value letter_id="E">0.055</value>
<value letter_id="F">0.036</value>
<value letter_id="G">0.090</value>
<value letter_id="H">0.018</value>
<value letter_id="I">0.057</value>
<value letter_id="K">0.052</value>
<value letter_id="L">0.092</value>
<value letter_id="M">0.027</value>
<value letter_id="N">0.041</value>
<value letter_id="P">0.041</value>
<value letter_id="Q">0.029</value>
<value letter_id="R">0.049</value>
<value letter_id="S">0.064</value>
<value letter_id="T">0.057</value>
<value letter_id="V">0.083</value>
<value letter_id="W">0.010</value>
<value letter_id="Y">0.027</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme common/adh.s -oc results/meme5 -mod zoops -protein -nmotifs 2 -minw 8 -nostatus </command_line>
<host>Timothys-iMac.rd.unr.edu</host>
<type>zoops</type>
<nmotifs>2</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<use_llr>0</use_llr>
<min_width>8</min_width>
<max_width>50</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>2</minsites>
<maxsites>33</maxsites>
<wnsites>0.8</wnsites>
<spmap>pam</spmap>
<spfuzz>120</spfuzz>
<prior>megap</prior>
<beta>49980</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>33</num_sequences>
<num_positions>9996</num_positions>
<seed>0</seed>
<ctfrac>-1</ctfrac>
<maxwords>-1</maxwords>
<strands>none</strands>
<priors_file>prior30.plib</priors_file>
<reason_for_stopping>Stopped because requested number of motifs (2) found.</reason_for_stopping>
<background_frequencies source="dataset with add-one prior applied">
<alphabet_array>
<value letter_id="A">0.111</value>
<value letter_id="C">0.012</value>
<value letter_id="D">0.050</value>
<value letter_id="E">0.055</value>
<value letter_id="F">0.036</value>
<value letter_id="G">0.090</value>
<value letter_id="H">0.018</value>
<value letter_id="I">0.057</value>
<value letter_id="K">0.052</value>
<value letter_id="L">0.092</value>
<value letter_id="M">0.027</value>
<value letter_id="N">0.041</value>
<value letter_id="P">0.041</value>
<value letter_id="Q">0.029</value>
<value letter_id="R">0.049</value>
<value letter_id="S">0.064</value>
<value letter_id="T">0.057</value>
<value letter_id="V">0.083</value>
<value letter_id="W">0.010</value>
<value letter_id="Y">0.027</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="KVALVTGASSGIGKATAKALAKEGAKVVL" alt="MEME-1" width="29" sites="30" ic="65.8" re="53.1" llr="1105" e_value="5.1e-168" bayes_threshold="8.12412" elapsed_time="3.470802">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-135</value>
<value letter_id="C">-319</value>
<value letter_id="D">-212</value>
<value letter_id="E">-22</value>
<value letter_id="F">-360</value>
<value letter_id="G">-140</value>
<value letter_id="H">85</value>
<value letter_id="I">-362</value>
<value letter_id="K">329</value>
<value letter_id="L">-140</value>
<value letter_id="M">-281</value>
<value letter_id="N">-173</value>
<value letter_id="P">52</value>
<value letter_id="Q">170</value>
<value letter_id="R">-22</value>
<value letter_id="S">-189</value>
<value letter_id="T">-51</value>
<value letter_id="V">-355</value>
<value letter_id="W">-331</value>
<value letter_id="Y">-281</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">11</value>
<value letter_id="C">121</value>
<value letter_id="D">-285</value>
<value letter_id="E">-215</value>
<value letter_id="F">-278</value>
<value letter_id="G">-396</value>
<value letter_id="H">72</value>
<value letter_id="I">-187</value>
<value letter_id="K">34</value>
<value letter_id="L">-257</value>
<value letter_id="M">-214</value>
<value letter_id="N">144</value>
<value letter_id="P">-331</value>
<value letter_id="Q">-160</value>
<value letter_id="R">-47</value>
<value letter_id="S">-234</value>
<value letter_id="T">18</value>
<value letter_id="V">235</value>
<value letter_id="W">148</value>
<value letter_id="Y">-272</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">186</value>
<value letter_id="C">-316</value>
<value letter_id="D">-673</value>
<value letter_id="E">-617</value>
<value letter_id="F">-402</value>
<value letter_id="G">-655</value>
<value letter_id="H">-547</value>
<value letter_id="I">99</value>
<value letter_id="K">-595</value>
<value letter_id="L">-322</value>
<value letter_id="M">30</value>
<value letter_id="N">-576</value>
<value letter_id="P">-598</value>
<value letter_id="Q">-547</value>
<value letter_id="R">-609</value>
<value letter_id="S">-523</value>
<value letter_id="T">-72</value>
<value letter_id="V">225</value>
<value letter_id="W">-507</value>
<value letter_id="Y">-475</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-165</value>
<value letter_id="C">-274</value>
<value letter_id="D">-583</value>
<value letter_id="E">-504</value>
<value letter_id="F">-3</value>
<value letter_id="G">-558</value>
<value letter_id="H">-390</value>
<value letter_id="I">194</value>
<value letter_id="K">-473</value>
<value letter_id="L">241</value>
<value letter_id="M">-175</value>
<value letter_id="N">-469</value>
<value letter_id="P">-484</value>
<value letter_id="Q">-391</value>
<value letter_id="R">-461</value>
<value letter_id="S">-415</value>
<value letter_id="T">-338</value>
<value letter_id="V">94</value>
<value letter_id="W">163</value>
<value letter_id="Y">-335</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-534</value>
<value letter_id="C">-363</value>
<value letter_id="D">-749</value>
<value letter_id="E">-712</value>
<value letter_id="F">-13</value>
<value letter_id="G">-774</value>
<value letter_id="H">-705</value>
<value letter_id="I">291</value>
<value letter_id="K">-703</value>
<value letter_id="L">-115</value>
<value letter_id="M">-341</value>
<value letter_id="N">-678</value>
<value letter_id="P">-687</value>
<value letter_id="Q">-663</value>
<value letter_id="R">-739</value>
<value letter_id="S">-662</value>
<value letter_id="T">-464</value>
<value letter_id="V">256</value>
<value letter_id="W">-605</value>
<value letter_id="Y">-566</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-381</value>
<value letter_id="C">-243</value>
<value letter_id="D">-425</value>
<value letter_id="E">-454</value>
<value letter_id="F">-425</value>
<value letter_id="G">-525</value>
<value letter_id="H">-357</value>
<value letter_id="I">-99</value>
<value letter_id="K">-368</value>
<value letter_id="L">-451</value>
<value letter_id="M">-311</value>
<value letter_id="N">-250</value>
<value letter_id="P">-429</value>
<value letter_id="Q">-310</value>
<value letter_id="R">-382</value>
<value letter_id="S">-17</value>
<value letter_id="T">388</value>
<value letter_id="V">-142</value>
<value letter_id="W">-398</value>
<value letter_id="Y">-446</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-191</value>
<value letter_id="C">-337</value>
<value letter_id="D">-328</value>
<value letter_id="E">-389</value>
<value letter_id="F">-495</value>
<value letter_id="G">336</value>
<value letter_id="H">-351</value>
<value letter_id="I">-514</value>
<value letter_id="K">-372</value>
<value letter_id="L">-557</value>
<value letter_id="M">-461</value>
<value letter_id="N">-284</value>
<value letter_id="P">-433</value>
<value letter_id="Q">-384</value>
<value letter_id="R">-375</value>
<value letter_id="S">-299</value>
<value letter_id="T">-414</value>
<value letter_id="V">-497</value>
<value letter_id="W">-388</value>
<value letter_id="Y">-440</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">205</value>
<value letter_id="C">242</value>
<value letter_id="D">-648</value>
<value letter_id="E">-644</value>
<value letter_id="F">-609</value>
<value letter_id="G">210</value>
<value letter_id="H">-567</value>
<value letter_id="I">-627</value>
<value letter_id="K">-660</value>
<value letter_id="L">-639</value>
<value letter_id="M">-563</value>
<value letter_id="N">-521</value>
<value letter_id="P">-482</value>
<value letter_id="Q">-522</value>
<value letter_id="R">-606</value>
<value letter_id="S">18</value>
<value letter_id="T">-365</value>
<value letter_id="V">-500</value>
<value letter_id="W">-585</value>
<value letter_id="Y">-629</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">118</value>
<value letter_id="C">-380</value>
<value letter_id="D">51</value>
<value letter_id="E">-306</value>
<value letter_id="F">-533</value>
<value letter_id="G">148</value>
<value letter_id="H">-270</value>
<value letter_id="I">-568</value>
<value letter_id="K">-320</value>
<value letter_id="L">-151</value>
<value letter_id="M">-508</value>
<value letter_id="N">87</value>
<value letter_id="P">-433</value>
<value letter_id="Q">-281</value>
<value letter_id="R">-392</value>
<value letter_id="S">199</value>
<value letter_id="T">-66</value>
<value letter_id="V">-538</value>
<value letter_id="W">-516</value>
<value letter_id="Y">-441</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-65</value>
<value letter_id="C">119</value>
<value letter_id="D">-37</value>
<value letter_id="E">-130</value>
<value letter_id="F">-349</value>
<value letter_id="G">34</value>
<value letter_id="H">-142</value>
<value letter_id="I">-353</value>
<value letter_id="K">159</value>
<value letter_id="L">-340</value>
<value letter_id="M">-273</value>
<value letter_id="N">-162</value>
<value letter_id="P">-289</value>
<value letter_id="Q">123</value>
<value letter_id="R">157</value>
<value letter_id="S">200</value>
<value letter_id="T">-49</value>
<value letter_id="V">-346</value>
<value letter_id="W">-324</value>
<value letter_id="Y">-272</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-197</value>
<value letter_id="C">-330</value>
<value letter_id="D">-310</value>
<value letter_id="E">-372</value>
<value letter_id="F">-105</value>
<value letter_id="G">327</value>
<value letter_id="H">-335</value>
<value letter_id="I">-499</value>
<value letter_id="K">-354</value>
<value letter_id="L">-543</value>
<value letter_id="M">-446</value>
<value letter_id="N">-266</value>
<value letter_id="P">-420</value>
<value letter_id="Q">-369</value>
<value letter_id="R">-129</value>
<value letter_id="S">-289</value>
<value letter_id="T">-154</value>
<value letter_id="V">-485</value>
<value letter_id="W">-372</value>
<value letter_id="Y">-424</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-205</value>
<value letter_id="C">-309</value>
<value letter_id="D">-512</value>
<value letter_id="E">-496</value>
<value letter_id="F">-45</value>
<value letter_id="G">-587</value>
<value letter_id="H">-457</value>
<value letter_id="I">343</value>
<value letter_id="K">-457</value>
<value letter_id="L">117</value>
<value letter_id="M">-171</value>
<value letter_id="N">-453</value>
<value letter_id="P">-514</value>
<value letter_id="Q">-427</value>
<value letter_id="R">-491</value>
<value letter_id="S">-439</value>
<value letter_id="T">-353</value>
<value letter_id="V">23</value>
<value letter_id="W">-387</value>
<value letter_id="Y">-367</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-580</value>
<value letter_id="C">-545</value>
<value letter_id="D">-561</value>
<value letter_id="E">-628</value>
<value letter_id="F">-691</value>
<value letter_id="G">346</value>
<value letter_id="H">-560</value>
<value letter_id="I">-746</value>
<value letter_id="K">-609</value>
<value letter_id="L">-754</value>
<value letter_id="M">-700</value>
<value letter_id="N">-528</value>
<value letter_id="P">-620</value>
<value letter_id="Q">-606</value>
<value letter_id="R">-602</value>
<value letter_id="S">-546</value>
<value letter_id="T">-643</value>
<value letter_id="V">-734</value>
<value letter_id="W">-581</value>
<value letter_id="Y">-645</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-67</value>
<value letter_id="C">-302</value>
<value letter_id="D">-227</value>
<value letter_id="E">-155</value>
<value letter_id="F">122</value>
<value letter_id="G">-141</value>
<value letter_id="H">171</value>
<value letter_id="I">-324</value>
<value letter_id="K">220</value>
<value letter_id="L">89</value>
<value letter_id="M">-267</value>
<value letter_id="N">-185</value>
<value letter_id="P">-308</value>
<value letter_id="Q">-101</value>
<value letter_id="R">183</value>
<value letter_id="S">-57</value>
<value letter_id="T">-217</value>
<value letter_id="V">-328</value>
<value letter_id="W">-325</value>
<value letter_id="Y">19</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">235</value>
<value letter_id="C">102</value>
<value letter_id="D">-18</value>
<value letter_id="E">115</value>
<value letter_id="F">-68</value>
<value letter_id="G">-147</value>
<value letter_id="H">27</value>
<value letter_id="I">-325</value>
<value letter_id="K">-248</value>
<value letter_id="L">-333</value>
<value letter_id="M">-271</value>
<value letter_id="N">-254</value>
<value letter_id="P">-384</value>
<value letter_id="Q">-218</value>
<value letter_id="R">-288</value>
<value letter_id="S">40</value>
<value letter_id="T">-231</value>
<value letter_id="V">-231</value>
<value letter_id="W">-321</value>
<value letter_id="Y">-336</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-67</value>
<value letter_id="C">137</value>
<value letter_id="D">-484</value>
<value letter_id="E">-406</value>
<value letter_id="F">-217</value>
<value letter_id="G">-448</value>
<value letter_id="H">-290</value>
<value letter_id="I">194</value>
<value letter_id="K">-373</value>
<value letter_id="L">84</value>
<value letter_id="M">126</value>
<value letter_id="N">-362</value>
<value letter_id="P">-395</value>
<value letter_id="Q">10</value>
<value letter_id="R">-368</value>
<value letter_id="S">-302</value>
<value letter_id="T">206</value>
<value letter_id="V">-3</value>
<value letter_id="W">-257</value>
<value letter_id="Y">117</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">260</value>
<value letter_id="C">215</value>
<value letter_id="D">-486</value>
<value letter_id="E">-446</value>
<value letter_id="F">-421</value>
<value letter_id="G">-324</value>
<value letter_id="H">-419</value>
<value letter_id="I">-408</value>
<value letter_id="K">-449</value>
<value letter_id="L">-425</value>
<value letter_id="M">-362</value>
<value letter_id="N">-423</value>
<value letter_id="P">-459</value>
<value letter_id="Q">-398</value>
<value letter_id="R">-445</value>
<value letter_id="S">10</value>
<value letter_id="T">-295</value>
<value letter_id="V">95</value>
<value letter_id="W">-408</value>
<value letter_id="Y">-457</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-264</value>
<value letter_id="C">-289</value>
<value letter_id="D">-40</value>
<value letter_id="E">85</value>
<value letter_id="F">-25</value>
<value letter_id="G">-357</value>
<value letter_id="H">85</value>
<value letter_id="I">60</value>
<value letter_id="K">247</value>
<value letter_id="L">34</value>
<value letter_id="M">-254</value>
<value letter_id="N">-174</value>
<value letter_id="P">-295</value>
<value letter_id="Q">-94</value>
<value letter_id="R">157</value>
<value letter_id="S">-186</value>
<value letter_id="T">-204</value>
<value letter_id="V">-121</value>
<value letter_id="W">-314</value>
<value letter_id="Y">18</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">43</value>
<value letter_id="C">-301</value>
<value letter_id="D">37</value>
<value letter_id="E">87</value>
<value letter_id="F">-338</value>
<value letter_id="G">-57</value>
<value letter_id="H">223</value>
<value letter_id="I">-83</value>
<value letter_id="K">-112</value>
<value letter_id="L">-6</value>
<value letter_id="M">-264</value>
<value letter_id="N">-163</value>
<value letter_id="P">-287</value>
<value letter_id="Q">54</value>
<value letter_id="R">128</value>
<value letter_id="S">-177</value>
<value letter_id="T">24</value>
<value letter_id="V">-45</value>
<value letter_id="W">151</value>
<value letter_id="Y">17</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-182</value>
<value letter_id="C">120</value>
<value letter_id="D">-592</value>
<value letter_id="E">-511</value>
<value letter_id="F">261</value>
<value letter_id="G">-594</value>
<value letter_id="H">-394</value>
<value letter_id="I">-46</value>
<value letter_id="K">-484</value>
<value letter_id="L">273</value>
<value letter_id="M">-152</value>
<value letter_id="N">-494</value>
<value letter_id="P">-486</value>
<value letter_id="Q">-385</value>
<value letter_id="R">-460</value>
<value letter_id="S">-453</value>
<value letter_id="T">-379</value>
<value letter_id="V">-278</value>
<value letter_id="W">-324</value>
<value letter_id="Y">13</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">143</value>
<value letter_id="C">136</value>
<value letter_id="D">-76</value>
<value letter_id="E">-395</value>
<value letter_id="F">-220</value>
<value letter_id="G">-148</value>
<value letter_id="H">264</value>
<value letter_id="I">87</value>
<value letter_id="K">-364</value>
<value letter_id="L">55</value>
<value letter_id="M">-160</value>
<value letter_id="N">-356</value>
<value letter_id="P">-393</value>
<value letter_id="Q">-302</value>
<value letter_id="R">-363</value>
<value letter_id="S">-81</value>
<value letter_id="T">-234</value>
<value letter_id="V">71</value>
<value letter_id="W">-259</value>
<value letter_id="Y">27</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">87</value>
<value letter_id="C">-309</value>
<value letter_id="D">-36</value>
<value letter_id="E">148</value>
<value letter_id="F">-347</value>
<value letter_id="G">-57</value>
<value letter_id="H">-140</value>
<value letter_id="I">-351</value>
<value letter_id="K">200</value>
<value letter_id="L">-338</value>
<value letter_id="M">-271</value>
<value letter_id="N">-161</value>
<value letter_id="P">-286</value>
<value letter_id="Q">123</value>
<value letter_id="R">45</value>
<value letter_id="S">16</value>
<value letter_id="T">24</value>
<value letter_id="V">-343</value>
<value letter_id="W">-322</value>
<value letter_id="Y">-270</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">66</value>
<value letter_id="C">-307</value>
<value letter_id="D">38</value>
<value letter_id="E">190</value>
<value letter_id="F">-344</value>
<value letter_id="G">-346</value>
<value letter_id="H">86</value>
<value letter_id="I">-349</value>
<value letter_id="K">57</value>
<value letter_id="L">-58</value>
<value letter_id="M">16</value>
<value letter_id="N">70</value>
<value letter_id="P">-284</value>
<value letter_id="Q">123</value>
<value letter_id="R">45</value>
<value letter_id="S">16</value>
<value letter_id="T">-198</value>
<value letter_id="V">-342</value>
<value letter_id="W">-320</value>
<value letter_id="Y">17</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-198</value>
<value letter_id="C">-331</value>
<value letter_id="D">-120</value>
<value letter_id="E">-371</value>
<value letter_id="F">-106</value>
<value letter_id="G">322</value>
<value letter_id="H">-334</value>
<value letter_id="I">-499</value>
<value letter_id="K">-134</value>
<value letter_id="L">-543</value>
<value letter_id="M">-445</value>
<value letter_id="N">-265</value>
<value letter_id="P">-116</value>
<value letter_id="Q">-368</value>
<value letter_id="R">-358</value>
<value letter_id="S">-289</value>
<value letter_id="T">-154</value>
<value letter_id="V">-485</value>
<value letter_id="W">-371</value>
<value letter_id="Y">-424</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">223</value>
<value letter_id="C">-118</value>
<value letter_id="D">-394</value>
<value letter_id="E">-332</value>
<value letter_id="F">101</value>
<value letter_id="G">-322</value>
<value letter_id="H">-282</value>
<value letter_id="I">-205</value>
<value letter_id="K">-6</value>
<value letter_id="L">-60</value>
<value letter_id="M">-201</value>
<value letter_id="N">-328</value>
<value letter_id="P">-398</value>
<value letter_id="Q">-274</value>
<value letter_id="R">-87</value>
<value letter_id="S">0</value>
<value letter_id="T">-231</value>
<value letter_id="V">-90</value>
<value letter_id="W">129</value>
<value letter_id="Y">138</value>