<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  spfun,
  min_width,
  max_width,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  hsfrac,
  maxwords,
  maxsize,
  csites,
  strands,
  priors_file,
  reason_for_stopping,
  back_order,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT maxwords (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT back_order (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                alt CDATA ""
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.11.3" release="Fri Feb 19 13:23:06 2016 -0800">
<training_set datafile="common/INO_up800.s" length="7">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<sequence id="sequence_0" name="CHO1" length="800" weight="1.000000" />
<sequence id="sequence_1" name="CHO2" length="800" weight="1.000000" />
<sequence id="sequence_2" name="FAS1" length="800" weight="1.000000" />
<sequence id="sequence_3" name="FAS2" length="800" weight="1.000000" />
<sequence id="sequence_4" name="ACC1" length="800" weight="1.000000" />
<sequence id="sequence_5" name="INO1" length="800" weight="1.000000" />
<sequence id="sequence_6" name="OPI3" length="800" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.304</value>
<value letter_id="C">0.196</value>
<value letter_id="G">0.196</value>
<value letter_id="T">0.304</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme common/INO_up800.s -oc results/meme7 -mod oops -dna -revcomp -bfile common/yeast.nc.6.freq -x_branch -nmotifs 2 -minw 8 -nostatus </command_line>
<host>Timothys-iMac.rd.unr.edu</host>
<type>oops</type>
<nmotifs>2</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<use_llr>0</use_llr>
<min_width>8</min_width>
<max_width>50</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>7</minsites>
<maxsites>7</maxsites>
<wnsites>0.8</wnsites>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>7</num_sequences>
<num_positions>5600</num_positions>
<seed>0</seed>
<ctfrac>-1</ctfrac>
<maxwords>-1</maxwords>
<strands>both</strands>
<priors_file></priors_file>
<reason_for_stopping>Stopped because requested number of motifs (2) found.</reason_for_stopping>
<background_frequencies source="common/yeast.nc.6.freq">
<alphabet_array>
<value letter_id="A">0.324</value>
<value letter_id="C">0.176</value>
<value letter_id="G">0.176</value>
<value letter_id="T">0.324</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="KGSKGCATGTGAAAABT" alt="MEME-1" width="17" sites="7" ic="23.0" re="24.1" llr="117" e_value="2.6e-002" bayes_threshold="9.61287" elapsed_time="1.399507">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">-30</value>
<value letter_id="G">170</value>
<value letter_id="T">-18</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-118</value>
<value letter_id="C">-945</value>
<value letter_id="G">229</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">129</value>
<value letter_id="G">129</value>
<value letter_id="T">-118</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-118</value>
<value letter_id="C">-945</value>
<value letter_id="G">170</value>
<value letter_id="T">-18</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">70</value>
<value letter_id="G">202</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">251</value>
<value letter_id="G">-945</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">162</value>
<value letter_id="C">-945</value>
<value letter_id="G">-945</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">-945</value>
<value letter_id="G">-945</value>
<value letter_id="T">162</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">-945</value>
<value letter_id="G">251</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-118</value>
<value letter_id="C">-945</value>
<value letter_id="G">-945</value>
<value letter_id="T">140</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">-945</value>
<value letter_id="G">251</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">140</value>
<value letter_id="C">-945</value>
<value letter_id="G">-30</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">162</value>
<value letter_id="C">-945</value>
<value letter_id="G">-945</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">114</value>
<value letter_id="C">-945</value>
<value letter_id="G">70</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">114</value>
<value letter_id="C">-945</value>
<value letter_id="G">-30</value>
<value letter_id="T">-118</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">70</value>
<value letter_id="G">129</value>
<value letter_id="T">-18</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">-945</value>
<value letter_id="G">-30</value>
<value letter_id="T">140</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.142857</value>
<value letter_id="G">0.571429</value>
<value letter_id="T">0.285714</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.142857</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.857143</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.428571</value>
<value letter_id="G">0.428571</value>
<value letter_id="T">0.142857</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.142857</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.571429</value>
<value letter_id="T">0.285714</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.285714</value>
<value letter_id="G">0.714286</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">1.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">1.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">1.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.142857</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.857143</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.857143</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.142857</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">1.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.714286</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.285714</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.714286</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.142857</value>
<value letter_id="T">0.142857</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.285714</value>
<value letter_id="G">0.428571</value>
<value letter_id="T">0.285714</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.142857</value>
<value letter_id="T">0.857143</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
[GT]G[CG][GT][GC]CATGTGAA[AG]A[GCT]T
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_5" position="618" strand="plus" pvalue="4.64e-10" >
<left_flank>GGCGGCTAAA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ATTGTCTATT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_2" position="90" strand="minus" pvalue="6.11e-09" >
<left_flank>TGCTTGGCTG</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTGGCCGTCG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_1" position="349" strand="minus" pvalue="6.52e-09" >
<left_flank>GAATAATGAA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>GTGGCAATTG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_4" position="78" strand="minus" pvalue="1.20e-08" >
<left_flank>CGCGCGCGGC</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTAACGGGCG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="635" strand="minus" pvalue="1.20e-08" >
<left_flank>ATCTTTAGAT</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>CAAAGGCGTG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_6" position="583" strand="plus" pvalue="3.84e-08" >
<left_flank>GTGTCAATGA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TGCACCGGTT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_3" position="562" strand="minus" pvalue="5.67e-08" >
<left_flank>AGGCGAATGA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>CGGGAGATAA</right_flank>
</contributing_site>
</contributing_sites>
</motif>
<motif id="motif_2" name="TCTGGCACAG" alt="MEME-2" width="10" sites="7" ic="14.5" re="16.7" llr="81" e_value="1.1e+002" bayes_threshold="9.62571" elapsed_time="2.778098">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">-945</value>
<value letter_id="G">70</value>
<value letter_id="T">114</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">251</value>
<value letter_id="G">-945</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-118</value>
<value letter_id="C">-945</value>
<value letter_id="G">-30</value>
<value letter_id="T">114</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">-945</value>
<value letter_id="G">251</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">-945</value>
<value letter_id="G">251</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">251</value>
<value letter_id="G">-945</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">140</value>
<value letter_id="C">-945</value>
<value letter_id="G">-30</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">229</value>
<value letter_id="G">-945</value>
<value letter_id="T">-118</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">82</value>
<value letter_id="C">-30</value>
<value letter_id="G">-30</value>
<value letter_id="T">-118</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">-30</value>
<value letter_id="G">229</value>
<value letter_id="T">-945</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.285714</value>
<value letter_id="T">0.714286</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">1.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.142857</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.142857</value>
<value letter_id="T">0.714286</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">1.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.857143</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.142857</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.857143</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.142857</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.571429</value>
<value letter_id="C">0.142857</value>
<value letter_id="G">0.142857</value>
<value letter_id="T">0.142857</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.142857</value>
<value letter_id="G">0.857143</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
[TG]CTGGCACAG
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_6" position="185" strand="minus" pvalue="3.28e-07" >
<left_flank>GAAAACCAGA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>ACCGTTGTCA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_4" position="231" strand="plus" pvalue="3.28e-07" >
<left_flank>CCAGTCGTAT</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>TATAGCCTAG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="558" strand="minus" pvalue="3.28e-07" >
<left_flank>ATATTCAGTG</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>AAGTCTGCAC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_5" position="282" strand="minus" pvalue="5.36e-06" >
<left_flank>ACGGTCTACG</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>TCGCATGTCT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_2" position="43" strand="plus" pvalue="6.33e-06" >
<left_flank>TACACGAGGT</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>TTCACTACTC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_3" position="184" strand="minus" pvalue="8.59e-06" >
<left_flank>TTCTTGCTTT</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>TTGACGGCTT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_1" position="412" strand="minus" pvalue="8.59e-06" >
<left_flank>TTTTGCCGTT</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>CCGTTCATTT</right_flank>
</contributing_site>
</contributing_sites>
</motif>
</motifs>
<scanned_sites_summary p_thresh="0.0001">
<scanned_sites sequence_id="sequence_0" pvalue="1.89e-07" num_sites="4"><scanned_site motif_id="motif_2" strand="plus" position="152" pvalue="1.11e-05"/>
<scanned_site motif_id="motif_2" strand="minus" position="558" pvalue="3.28e-07"/>
<scanned_site motif_id="motif_1" strand="minus" position="606" pvalue="2.43e-05"/>
<scanned_site motif_id="motif_1" strand="minus" position="635" pvalue="1.20e-08"/>
</scanned_sites>
<scanned_sites sequence_id="sequence_1" pvalue="2.32e-06" num_sites="2"><scanned_site motif_id="motif_1" strand="minus" position="349" pvalue="6.52e-09"/>
<scanned_site motif_id="motif_2" strand="minus" position="412" pvalue="8.59e-06"/>
</scanned_sites>
<scanned_sites sequence_id="sequence_2" pvalue="1.64e-06" num_sites="2"><scanned_site motif_id="motif_2" strand="plus" position="43" pvalue="6.33e-06"/>
<scanned_site motif_id="motif_1" strand="minus" position="90" pvalue="6.11e-09"/>
</scanned_sites>
<scanned_sites sequence_id="sequence_3" pvalue="1.75e-05" num_sites="2"><scanned_site motif_id="motif_2" strand="minus" position="184" pvalue="8.59e-06"/>
<scanned_site motif_id="motif_1" strand="minus" position="562" pvalue="5.67e-08"/>
</scanned_sites>
<scanned_sites sequence_id="sequence_4" pvalue="1.89e-07" num_sites="2"><scanned_site motif_id="motif_1" strand="minus" position="78" pvalue="1.20e-08"/>
<scanned_site motif_id="motif_2" strand="plus" position="231" pvalue="3.28e-07"/>
</scanned_sites>
<scanned_sites sequence_id="sequence_5" pvalue="1.22e-07" num_sites="4"><scanned_site motif_id="motif_2" strand="minus" position="282" pvalue="5.36e-06"/>
<scanned_site motif_id="motif_1" strand="plus" position="548" pvalue="9.62e-05"/>
<scanned_site motif_id="motif_1" strand="plus" position="569" pvalue="5.31e-05"/>
<scanned_site motif_id="motif_1" strand="plus" position="618" pvalue="4.64e-10"/>
</scanned_sites>
<scanned_sites sequence_id="sequence_6" pvalue="5.70e-07" num_sites="3"><scanned_site motif_id="motif_2" strand="minus" position="185" pvalue="3.28e-07"/>
<scanned_site motif_id="motif_1" strand="plus" position="583" pvalue="3.84e-08"/>
<scanned_site motif_id="motif_1" strand="minus" position="632" pvalue="3.61e-05"/>
</scanned_sites>
</scanned_sites_summary>
</MEME>
